
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - $DB_PORT:5432
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata

volumes:
  postgres:

